### ISSUE TITLE
Rótulo do perfil causa erro de retorno do SimilarDocs

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/SimilarDocs#1]
O erro ocorre quando o rótulo tem:

- Palavras compostas
- Palavras com diacríticos

**Comment by heitorbarbieri** [comment]
O sistema quando recebe uma requisição HTTP indicando o encoding correto da mensagem, funciona corretamente. Testado com palavras compostas e e com palavras com diacríticos.
