### ISSUE TITLE
Priorizar documentos mais novos quando a similaridade for alta

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/SimilarDocs#10]

**Comment by heitorbarbieri** [comment]
Para o ordenamento das datas dos documentos, utilizou-se elemento <entry_date> presente nos xmls utilizados na indexação. A data apresentada em cada documento no iahx corresponde ao elemento <dp> do xml, mas como este elemento não está presente em todos os xmls, por ex os do lis, optou-se por utilizar o <entry_date> por estar presente em todos os xmls.

O algoritmo utilizado para a priorização dos documentos é o seguinte:
 a) recuperam-se os documentos similares a um documento
 b) destes documentos, todos aqueles com ranking igual ou superior a 80 são ordenados por data
 c) se ainda faltarem documentos para se completar a quantidade mínima padrão (10 documentos), utlizam-se os documentos com ranking menores de 80 em ordem decrescente.
