### ISSUE TITLE
Permitir filtrar o resultado por fonte de informação

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/SimilarDocs#23]
Criar parâmetro na chamada do serviço que permita recuperar documentos similares somente de uma fonte de informação.

**Comment by heitorbarbieri** [comment]
O serviço de documentos similares (http://similardocs.bireme.org/) possui o parâmetro opcional "sources=" na função:

SDService?adhocSimilarDocs=<text>[&outFields=<field>,...,<field>][&maxDocs=<num>][&sources=<src>,...,<src>][&lastDays=<number_of_days>][&explain=<bool>]

que permite restringir em quais fontes de informação os documentos similares devem ser buscados.

Na função utlizada pela MinhaBVS:
SDService?psId=<id>&getSimDocs=<profile>,..,<profile>[&outFields=<field>,...,<field>]
o parâmetro sources=  não existe pois ele está implicitamente "cravado" com os valores ("MEDLINE", "LILACS", "LIS", "colecionaSUS")

Os valores aceitos no parâmetro sources= são os mesmos do campo db dos arquivos xml de entrada do portal (serverofi5:/bases/iahx/xml-inbox/regional) cujos valores atualmente são:

ACERVOFAR
ACV-CRTAIDS
adolecbr
AHM-Acervo
AHM-Producao
AIM
ARCA
ARGMSAL
AROUCA
ATTI-Producao
BBO
BDENF
BDNPAR
BDS
bibliografia
BIGG
BINACIS
BINAME
bioeticacol
bivipsil
BRISA
BVSAM
BVSCARGA
BVSDIP
BVSEPS
BVSNACUY
BVSPS
BVSVS
CAB-Producao
CACHOEIRINHA-Acervo
CACHOEIRINHA-Producao
CAMPOLIMPO-Acervo
CAMPOLIMPO-Producao
CDIC
CEINFO-Producao
CEP-Producao
CESTEH
CGP-Producao
CidSaude
CLAVES
COGERH-Producao
colecionaSUS
COLNAL
COMURGE-Producao
CONASS
CORAS-Producao
COVISA-Acervo
COVISA-Producao
CPQAM
CPQRR
CRAEA-Producao
CRSCENTROOESTE-Producao
CRSCENTRO-Producao
CRSLESTE-Producao
CRSNORTE-Producao
CRSOESTE-Producao
CRSSUDESTE-Producao
CRSSUL-Producao
CSMRCAA-Producao
CUMED
DESASTRES
DST_AIDS-Acervo
DST_AIDS-Producao
ECOS
ECUADOR
Educa
EMS-Acervo
EMS-Producao
ENSP
Especialista
FIOCRUZ
GHL
HANSENIASE
HISA
HomeoIndex
HSPM-Acervo
HSPM-Producao
IBECS
IEC
ILMD
IMEMR
IMSEAR
inca
INDEXPSI
Instituicao
InstitutionalDB
INTEGRALIDADE
LIBOCS
LILACS
LIPECS
LIS
LIS-ES-CIUD
LIS-ES-PROF
LIVECS
MAEPAULISTANA-Producao
MBOIMIRIM-Producao
MedCarib
MEDLINE
MINSA
MMyP
MS
MTYCI
MULTIMEDIA
NP-Producao
OPSURU
PAHO
PAHOIRIS
PANAMA
PERNAL
PIE
Projeto
Puerto-Rico
redbvs
repositorio
RHS
SAMU-Producao
SAOLUIZGONZAGA-Producao
SES-SP
SESSP-ACVSES
SESSP-AGITASPPROD
SESSP-CRATOD
SESSP-CTDPROD
SESSP-CVEPROD
SESSP-CVS-ACERVO
SESSP-CVSPROD
SESSP-DSTPROD
SESSP-ESPECIALIZACAOSESPROD
SESSP-FOLHETOCTD
SESSP-HMLMBACERVO
SESSP-HMLMBPROD
SESSP-IALACERVO
SESSP-IALPROD
SESSP-IBACERVO
SESSP-IBPROD
SESSP-ICFPROD
SESSP-IDPCPROD
SESSP-IIERPROD
SESSP-ILSLACERVO
SESSP-ILSLPROD
SESSP-IPACERVO
SESSP-IPGGACERVO
SESSP-IPGGPROD
SESSP-IPPROD
SESSP-ISACERVO
SESSP-ISPROD
SESSP-PAPSESSP
SESSP-RARASAUDE
SESSP-SUCENPROD
SESSP-TESESESSP
SMS-SP
SMULILACS
SMUVIDEOS

**Comment by viniciusandrade** [comment]
@heitorbarbieri obrigado pela implementação.

Adicionalmente gostaria de solicitar a inclusão de um filtro com o elemento **instance** do XML de entrada do portal.

Este elemento é gerado na entrada e corresponde ao agrupamento lógico de várias bases de dados contidas em um portal.

Obrigado.

**Comment by heitorbarbieri** [comment]
@viniciusandrade ,

Implementado o parâmetro o opcional "instances=" na função:

SDService?adhocSimilarDocs=[&outFields=,...,][&maxDocs=][&sources=,...,][&instances=,...,][&lastDays=<number_of_days>][&explain=]

que permite restringir em quais fontes de informação os documentos similares devem ser buscados de acordo com o campo 'instance' do XML.

Na função utlizada pela MinhaBVS:
SDService?psId=&getSimDocs=,..,[&outFields=,...,]
o parâmetro sources= não existe pois ele poderia estar implicitamente "cravado" com os valores padões. Atualmente ele não contém nenhum valor.

Os valores aceitos no parâmetro instances= são os mesmos do campo 'instance' dos arquivos xml de entrada do portal (serverofi5:/bases/iahx/xml-inbox/regional) cujos valores atualmente são:

adolec
aps
bibliosus
bioetica
BiViPsiL
brasil
bvscolombia
bvsecuador
bvsespana
bvsnacuy
bvssmu
carpha
conass
economia
enfermeriauy
fioc_aleitamento_materno
fioc_doencas_infecciosas_parasitarias
fioc_educacao_profissional_saude
fioc_integralidade_saude
fioc_pensamento_social
fioc_portal_thesis
fiocruz
fioc_violencia_saude
fronteriza
ghl
hanseniase
homeopatia
IEC
mtc
odontologia
oncologiauy
panama
paraguay
perinatal
psbe
recursos_humanos
redbvs
regional
SES-SP
sms
uruguai
uruguaiodonto
veterinaria

Vale ressaltar que os parâmetros sources= e instances=  podem atuar conjuntamente permitindo que se filtre os resultados por uma base de dados em especial dentre os documentos pertencentes a uma determinada instância.

Por favor, testem os dois parâmetros para certificarmos de que estão corretamente implementados. Obrigado.
