### ISSUE TITLE
Documento duplicado no serviço de similares

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/SimilarDocs#26]
Exemplo do erro:

http://sites.bvsalud.org/legislacion/factores-de-riesgo/resource/?id=leisref.act.2531

O documento "Designed for addiction how the tobacco industry has made cigarettes more addictive, more attractive to kids and even more deadly" aparece duas vezes, link http://pesquisa.bvsalud.org/portal/resource/en/biblio-940125

**Comment by heitorbarbieri** [comment]
Resolvido no commit  fcb4eb1
