### ISSUE TITLE
Duplicação de perfil de usuário no índice Lucene

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/SimilarDocs#37]
Índice topIndex com dois registros ativos.

--------- id=648 -------------------------------------
[id]=XXXXX_violência  psicológica
[creation_time]=1509050917061
[update_time]=0
[user]=XXXXX
[prof_name]=violência  psicológica
[prof_content]=contra mulher psicologica violencia

--------- id=1629 -------------------------------------
[id]=XXXXX_violência psicológica
[creation_time]=1509051079889
[update_time]=1573151261371
[user]=XXXXXX
[prof_name]=violência psicológica
[prof_content]=contra mulher psicologica violencia
[sd_id]=26503615
[sd_id]=6757783
[sd_id]=6760781
[sd_id]=6760144
[sd_id]=6750459
[sd_id]=6762629
[sd_id]=6759134
[sd_id]=6764686
[sd_id]=6752243
[sd_id]=6749370

**Comment by renatomurasaki** [comment]
@heitorbarbieri creio que isso já foi resolvido, certo?

**Comment by heitorbarbieri** [comment]
Issue antigo, este problema não ocorrerá novamente pois o houve regeração de indice
