### ISSUE TITLE
Substituição do tamanho padrão dos ngrams de 3 (trigramas) para 4 (tetragramas)

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/SimilarDocs#6]
Muitos documentos relacionados recuperados apresentam baixo índice de similaridade conforme avaliação por parte de usuários. Embora os mesmos apresentem alguns trigramas presentes no perfil, na realidade tais trigramas compõem palavras que não têm o mesmo significado das palavras do perfil.
Espera-se que com o aumento de trigramas para tetragramas, o número de recuperações caiam, mas a qualidade dos mesmos aumentem pois a probabilidade de um tetragrama ocorrer em várias palavras é menor que um trigrama, aumentanto, portanto, a chance de a palavra ser a correta.

**Comment by heitorbarbieri** [comment]
Fica faltando a análise dos resultados de recuperação para a confirmação ou não da melhoria da qualidade de recuperação.

**Comment by renatomurasaki** [comment]
@heitorbarbieri entendo que ficou melhor com tetragramas, correto Favor atualizar

**Comment by heitorbarbieri** [comment]
O algoritmo foi modificado de forma a inicialmente tentar tokenizar a expressão de busca com ngrama de tamanho 5, se não for possível (devido ao tamanho da palavra) usa-se o tamanho 4 e se ainda não for possível utiliza-se o tamanho 3. 
Verificou-se nos testes que o resultado obtido é melhor utilizando este esquema, mas com o inconveniente de palavras escritas incorretamente poderem não ser reconhecidas tão facilmente como ocorre quando se utiliza o tamanho 3.
Servidor de produção atualizado.
