### ISSUE TITLE
Instalação inicial do sistema em servidor de produção

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/SimilarDocs#7]
- [x] - Checar se instalado Tomcat em servidor de produção
- [x] - Verificação do Tomcat instalado
- [x] - Instalação do SimilarDocs no Tomcat
- [x] - Criação do mecanismo de cópia de índices do servidor serverofi5
- [x] - Criação do mecanismo de substituição dos índices antigos pelos novos
- [x] - Teste do sistema
- [x] - Divulgação da nova url para atualização da mesma na Plataforma de Serviços

**Comment by renatomurasaki** [comment]
@heitorbarbieri favor atualizar
